<?php

declare(strict_types=1);

/*
 * This file is part of the playwright-php/playwright package.
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

namespace PlaywrightPHP\Tests\Integration\Page;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use PlaywrightPHP\Configuration\PlaywrightConfig;
use PlaywrightPHP\Page\Page;
use PlaywrightPHP\Screenshot\ScreenshotHelper;
use PlaywrightPHP\Testing\PlaywrightTestCaseTrait;
use PlaywrightPHP\Tests\Support\RouteServerTestTrait;

#[CoversClass(Page::class)]
class ScreenshotIntegrationTest extends TestCase
{
    use PlaywrightTestCaseTrait;
    use RouteServerTestTrait;

    private string $screenshotTestDir;

    public static function setUpBeforeClass(): void
    {
    }

    public static function tearDownAfterClass(): void
    {
    }

    public function setUp(): void
    {
        $this->screenshotTestDir = sys_get_temp_dir().'/playwright-screenshot-test-'.uniqid('', true);
        mkdir($this->screenshotTestDir, 0755, true);

        $config = new PlaywrightConfig(
            screenshotDir: $this->screenshotTestDir,
            headless: true
        );

        $this->setUpPlaywright(null, $config);
        $this->installRouteServer($this->page, [
            '/index.html' => <<<'HTML'
                <!DOCTYPE html>
                <html>
                <head><title>Screenshot Test Page</title></head>
                <body>
                    <h1>Hello Screenshot World!</h1>
                    <div style="width:100px;height:100px;background:red;"></div>
                    <a href="/page2.html">Go to Page 2</a>
                </body>
                </html>
            HTML,
            '/page2.html' => <<<'HTML'
                <!DOCTYPE html>
                <html>
                <head><title>Page 2 - Screenshot Test</title></head>
                <body>
                    <h2>This is Page 2</h2>
                    <div style="width:200px;height:50px;background:blue;"></div>
                </body>
                </html>
            HTML,
        ]);
        $this->page->goto($this->routeUrl('/index.html'));
    }

    public function tearDown(): void
    {
        $this->tearDownPlaywright();

        if (is_dir($this->screenshotTestDir)) {
            array_map('unlink', glob($this->screenshotTestDir.'/*.*'));
            rmdir($this->screenshotTestDir);
        }
    }

    #[Test]
    public function itTakesAutoGeneratedScreenshot(): void
    {
        $screenshotPath = $this->page->screenshot();

        $this->assertIsString($screenshotPath);
        $this->assertFileExists($screenshotPath);
        $this->assertStringStartsWith($this->screenshotTestDir, $screenshotPath);

        $basename = basename($screenshotPath);
        $this->assertMatchesRegularExpression(
            '/^\d{8}_\d{6}_\d{3}_localhost.*\.png$/',
            $basename
        );

        $this->assertPngFileIsValid($screenshotPath);
    }

    #[Test]
    public function itTakesScreenshotWithCustomPath(): void
    {
        $customPath = $this->screenshotTestDir.'/custom-screenshot.png';

        $result = $this->page->screenshot($customPath);

        $this->assertEquals($customPath, $result);
        $this->assertFileExists($customPath);
        $this->assertPngFileIsValid($customPath);
    }

    #[Test]
    public function itTakesScreenshotAuto(): void
    {
        $screenshotPath = $this->page->screenshotAuto('custom-test');

        $this->assertIsString($screenshotPath);
        $this->assertFileExists($screenshotPath);
        $this->assertStringContainsString('custom-test', basename($screenshotPath));
        $this->assertPngFileIsValid($screenshotPath);
    }

    #[Test]
    public function itGeneratesUniqueFilenames(): void
    {
        $screenshots = [];

        for ($i = 0; $i < 3; ++$i) {
            $screenshots[] = $this->page->screenshot();
            usleep(1000);
        }

        $uniqueScreenshots = array_unique($screenshots);
        $this->assertCount(3, $uniqueScreenshots);

        foreach ($screenshots as $screenshot) {
            $this->assertFileExists($screenshot);
            $this->assertPngFileIsValid($screenshot);
        }
    }

    #[Test]
    public function itHandlesDifferentUrlsInFilenames(): void
    {
        $this->page->goto($this->routeUrl('/page2.html'));

        $screenshotPath = $this->page->screenshot();
        $basename = basename($screenshotPath);

        $this->assertStringContainsString('page2', $basename);
        $this->assertFileExists($screenshotPath);
        $this->assertPngFileIsValid($screenshotPath);
    }

    #[Test]
    public function itTakesFullPageScreenshot(): void
    {
        $screenshotPath = $this->page->screenshot(null, ['fullPage' => true]);

        $this->assertIsString($screenshotPath);
        $this->assertFileExists($screenshotPath);
        $this->assertPngFileIsValid($screenshotPath);
    }

    #[Test]
    public function itReturnsPathWhenExplicitPath(): void
    {
        $screenshotPath = $this->screenshotTestDir.'/explicit-test.png';
        $result = $this->page->screenshot($screenshotPath);

        $this->assertEquals($screenshotPath, $result);

        $this->assertFileExists($screenshotPath);
        $this->assertPngFileIsValid($screenshotPath);
    }

    #[Test]
    public function itUsesConfiguredScreenshotDirectory(): void
    {
        $screenshotPath = $this->page->screenshot();

        $this->assertStringStartsWith($this->screenshotTestDir, $screenshotPath);
    }

    #[Test]
    public function itCleansUpOldScreenshots(): void
    {
        for ($i = 0; $i < 5; ++$i) {
            $oldFile = $this->screenshotTestDir."/old_screenshot_{$i}.png";
            file_put_contents($oldFile, 'fake png data');

            touch($oldFile, time() - 7200);
        }

        for ($i = 0; $i < 2; ++$i) {
            $this->page->screenshot();
        }

        $cleaned = ScreenshotHelper::cleanupOldScreenshots($this->screenshotTestDir, 3600);

        $this->assertEquals(5, $cleaned);

        $remaining = glob($this->screenshotTestDir.'/*.png');
        $this->assertCount(2, $remaining);
    }

    #[Test]
    public function itGetsDirectoryInfo(): void
    {
        $this->page->screenshot();
        $this->page->screenshotAuto('test1');
        $this->page->screenshotAuto('test2');

        $info = ScreenshotHelper::getDirectoryInfo($this->screenshotTestDir);

        $this->assertEquals(3, $info['count']);
        $this->assertGreaterThan(0, $info['totalSize']);
        $this->assertIsString($info['oldestFile']);
        $this->assertIsString($info['newestFile']);
    }

    private function assertPngFileIsValid(string $path): void
    {
        $this->assertFileExists($path);

        $content = file_get_contents($path);
        $this->assertNotEmpty($content);

        $pngSignature = "\x89\x50\x4E\x47\x0D\x0A\x1A\x0A";
        $this->assertEquals($pngSignature, substr($content, 0, 8), 'File is not a valid PNG');

        $this->assertGreaterThan(1024, strlen($content), 'PNG file seems too small');
    }

    private static function findFreePort(): int
    {
        return 0;
    }
}
