<?php

declare(strict_types=1);

/*
 * This file is part of the playwright-php/playwright package.
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

namespace PlaywrightPHP\Tests\Integration\Page;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use PlaywrightPHP\Configuration\PlaywrightConfig;
use PlaywrightPHP\Page\Page;
use PlaywrightPHP\Support\ScreenshotHelper;
use PlaywrightPHP\Testing\PlaywrightTestCaseTrait;
use Symfony\Component\Process\Process;

#[CoversClass(Page::class)]
class ScreenshotIntegrationTest extends TestCase
{
    use PlaywrightTestCaseTrait;

    private static ?Process $server = null;
    private static string $docroot;
    private static int $port;
    private string $screenshotTestDir;

    public static function setUpBeforeClass(): void
    {
        self::$docroot = sys_get_temp_dir().'/playwright-php-screenshot-tests-'.uniqid('', true);
        mkdir(self::$docroot);

        // Create test HTML files
        file_put_contents(self::$docroot.'/index.html', '
            <!DOCTYPE html>
            <html>
            <head><title>Screenshot Test Page</title></head>
            <body>
                <h1>Hello Screenshot World!</h1>
                <div style="width:100px;height:100px;background:red;"></div>
                <a href="/page2.html">Go to Page 2</a>
            </body>
            </html>
        ');

        file_put_contents(self::$docroot.'/page2.html', '
            <!DOCTYPE html>
            <html>
            <head><title>Page 2 - Screenshot Test</title></head>
            <body>
                <h2>This is Page 2</h2>
                <div style="width:200px;height:50px;background:blue;"></div>
            </body>
            </html>
        ');

        self::$port = self::findFreePort();
        self::$server = new Process(['php', '-S', 'localhost:'.self::$port, '-t', self::$docroot]);
        self::$server->start();
        usleep(100000); // Give server time to start
    }

    public static function tearDownAfterClass(): void
    {
        if (self::$server && self::$server->isRunning()) {
            self::$server->stop();
        }
        array_map('unlink', glob(self::$docroot.'/*.*'));
        rmdir(self::$docroot);
    }

    public function setUp(): void
    {
        // Create custom screenshot directory for this test
        $this->screenshotTestDir = sys_get_temp_dir().'/playwright-screenshot-test-'.uniqid('', true);
        mkdir($this->screenshotTestDir, 0755, true);

        // Set up Playwright with custom screenshot directory
        $config = new PlaywrightConfig(
            screenshotDir: $this->screenshotTestDir,
            headless: true
        );

        $this->setUpPlaywright(null, $config);
        $this->page->goto('http://localhost:'.self::$port.'/index.html');
    }

    public function tearDown(): void
    {
        $this->tearDownPlaywright();

        // Clean up screenshot test directory
        if (is_dir($this->screenshotTestDir)) {
            array_map('unlink', glob($this->screenshotTestDir.'/*.*'));
            rmdir($this->screenshotTestDir);
        }
    }

    #[Test]
    public function itTakesAutoGeneratedScreenshot(): void
    {
        // Take screenshot with auto-generated filename
        $screenshotPath = $this->page->screenshot();

        $this->assertIsString($screenshotPath);
        $this->assertFileExists($screenshotPath);
        $this->assertStringStartsWith($this->screenshotTestDir, $screenshotPath);

        // Check filename pattern: YYYYMMDD_HHMMSS_mmm_localhost.png
        $basename = basename($screenshotPath);
        $this->assertMatchesRegularExpression(
            '/^\d{8}_\d{6}_\d{3}_localhost.*\.png$/',
            $basename
        );

        // Verify it's a valid PNG file
        $this->assertPngFileIsValid($screenshotPath);
    }

    #[Test]
    public function itTakesScreenshotWithCustomPath(): void
    {
        $customPath = $this->screenshotTestDir.'/custom-screenshot.png';

        // Take screenshot with explicit path
        $result = $this->page->screenshot($customPath);

        $this->assertEquals($customPath, $result); // Returns the path when explicit path provided
        $this->assertFileExists($customPath);
        $this->assertPngFileIsValid($customPath);
    }

    #[Test]
    public function itTakesScreenshotAuto(): void
    {
        // Take screenshot with custom suffix
        $screenshotPath = $this->page->screenshotAuto('custom-test');

        $this->assertIsString($screenshotPath);
        $this->assertFileExists($screenshotPath);
        $this->assertStringContainsString('custom-test', basename($screenshotPath));
        $this->assertPngFileIsValid($screenshotPath);
    }

    #[Test]
    public function itGeneratesUniqueFilenames(): void
    {
        $screenshots = [];

        // Take multiple screenshots quickly
        for ($i = 0; $i < 3; ++$i) {
            $screenshots[] = $this->page->screenshot();
            usleep(1000); // Small delay to ensure different milliseconds
        }

        // All filenames should be unique
        $uniqueScreenshots = array_unique($screenshots);
        $this->assertCount(3, $uniqueScreenshots);

        // All files should exist
        foreach ($screenshots as $screenshot) {
            $this->assertFileExists($screenshot);
            $this->assertPngFileIsValid($screenshot);
        }
    }

    #[Test]
    public function itHandlesDifferentUrlsInFilenames(): void
    {
        // Navigate to different page
        $this->page->goto('http://localhost:'.self::$port.'/page2.html');

        $screenshotPath = $this->page->screenshot();
        $basename = basename($screenshotPath);

        // Should include page2 in filename
        $this->assertStringContainsString('page2', $basename);
        $this->assertFileExists($screenshotPath);
        $this->assertPngFileIsValid($screenshotPath);
    }

    #[Test]
    public function itTakesFullPageScreenshot(): void
    {
        $screenshotPath = $this->page->screenshot(null, ['fullPage' => true]);

        $this->assertIsString($screenshotPath);
        $this->assertFileExists($screenshotPath);
        $this->assertPngFileIsValid($screenshotPath);
    }

    #[Test]
    public function itReturnsPathWhenExplicitPath(): void
    {
        // Call screenshot with explicit path in test directory
        $screenshotPath = $this->screenshotTestDir.'/explicit-test.png';
        $result = $this->page->screenshot($screenshotPath);

        // Should return the path that was provided
        $this->assertEquals($screenshotPath, $result);

        // File should exist
        $this->assertFileExists($screenshotPath);
        $this->assertPngFileIsValid($screenshotPath);
    }

    #[Test]
    public function itUsesConfiguredScreenshotDirectory(): void
    {
        $screenshotPath = $this->page->screenshot();

        // Should use the configured screenshot directory
        $this->assertStringStartsWith($this->screenshotTestDir, $screenshotPath);
    }

    #[Test]
    public function itCleansUpOldScreenshots(): void
    {
        // Create some old screenshots
        for ($i = 0; $i < 5; ++$i) {
            $oldFile = $this->screenshotTestDir."/old_screenshot_{$i}.png";
            file_put_contents($oldFile, 'fake png data');
            // Make them old
            touch($oldFile, time() - 7200); // 2 hours ago
        }

        // Create recent screenshots
        for ($i = 0; $i < 2; ++$i) {
            $this->page->screenshot();
        }

        // Clean up old screenshots (max age: 1 hour)
        $cleaned = ScreenshotHelper::cleanupOldScreenshots($this->screenshotTestDir, 3600);

        $this->assertEquals(5, $cleaned); // Should have cleaned 5 old files

        // Check that recent screenshots still exist
        $remaining = glob($this->screenshotTestDir.'/*.png');
        $this->assertCount(2, $remaining); // Only 2 recent ones should remain
    }

    #[Test]
    public function itGetsDirectoryInfo(): void
    {
        // Take a few screenshots
        $this->page->screenshot();
        $this->page->screenshotAuto('test1');
        $this->page->screenshotAuto('test2');

        $info = ScreenshotHelper::getDirectoryInfo($this->screenshotTestDir);

        $this->assertEquals(3, $info['count']);
        $this->assertGreaterThan(0, $info['totalSize']);
        $this->assertIsString($info['oldestFile']);
        $this->assertIsString($info['newestFile']);
    }

    private function assertPngFileIsValid(string $path): void
    {
        $this->assertFileExists($path);

        $content = file_get_contents($path);
        $this->assertNotEmpty($content);

        // Check PNG signature (first 8 bytes)
        $pngSignature = "\x89\x50\x4E\x47\x0D\x0A\x1A\x0A";
        $this->assertEquals($pngSignature, substr($content, 0, 8), 'File is not a valid PNG');

        // Ensure file has reasonable size (> 1KB)
        $this->assertGreaterThan(1024, strlen($content), 'PNG file seems too small');
    }

    private static function findFreePort(): int
    {
        $sock = socket_create_listen(0);
        socket_getsockname($sock, $addr, $port);
        socket_close($sock);

        return $port;
    }
}
